### ISSUE TITLE
Add the official Docker image.

### ISSUE THREAD

**Issue by mariushosting** [dh1011/subscription-manager#1]
Hello! Awesome project!

Can you please add the official Docker image to the project?

**Comment by dh1011** [comment]
Hi @mariushosting,
Great suggestion. I’ve just pushed the first Docker image to Docker Hub at [dh1011/subscription-manager](https://hub.docker.com/r/dh1011/subscription-manager).
Thanks 🙌

**Comment by limdul** [comment]
Any hope for you to add an arm64 docker image?

**Comment by dh1011** [comment]
Hi @limdul ,
I have pushed the arm64 image to [dh1011/subscription-manager:latest](https://hub.docker.com/r/dh1011/subscription-manager/tags)

**Comment by limdul** [comment]
> Hi @limdul , I have pushed the arm64 image to [dh1011/subscription-manager:latest](https://hub.docker.com/r/dh1011/subscription-manager/tags)

Thank you, seems to be running on my RasberryPi 5 now. Will test more when I'm home.
