### ISSUE TITLE
Error "Invalid Host header" behind traefik-reverse-proxy

### ISSUE THREAD

**Issue by matze939939** [dh1011/subscription-manager#3]
When I try to make the container accessible via traefik (https) I get the error "Invalid Host header". how can I solve this?

**Comment by LeonaLucille** [comment]
I passed  "- DANGEROUSLY_DISABLE_HOST_CHECK=true" as an environment variable in the docker-compose file. That did the trick

**Comment by uatevahr** [comment]
> I passed "- DANGEROUSLY_DISABLE_HOST_CHECK=true" as an environment variable in the docker-compose file. That did the trick

This worked for me. Thank you
