### ISSUE TITLE
Option to deselect a subscription from calculation

### ISSUE THREAD

**Issue by CopyAce** [dh1011/subscription-manager#4]
If there was a check box to deselect items from the Subscriptions List, so that they were no longer calculated towards the weekly, monthly, and yearly totals, it would allow users to sort the monthly cost by the type of service. For example I would deselect, Verizon Cell Phone service, so I could only see the remaining monthly cost of my streaming services.

**Comment by dh1011** [comment]
Hi @CopyAce,
Great idea 👌! I've implemented the feature in the [feature/subscriptionlist-improve](https://github.com/dh1011/subscription-manager/tree/feature/subscriptionlist-improve) branch. I'll be creating a new Docker image soon, but in the meantime, feel free to clone the repository and build it locally. This update also includes the feature mentioned in your issue #5.
