### ISSUE TITLE
Not able to run docker run command 

### ISSUE THREAD

**Issue by bettergenius1** [dh1011/subscription-manager#8]
docker run -p 3000:3000 dh1011/subscription-manager

I run the above commaned in proxmox cli and i get the below error

WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested
exec /usr/local/bin/docker-entrypoint.sh: exec format error

I am on a amd system.
I have also tried it in dockge with the screenshot below 

![subscription manager ](https://github.com/user-attachments/assets/a73c3616-5d88-4e35-8dfb-2d4acacf1f0f)

![subscription manager2 ](https://github.com/user-attachments/assets/4606a036-03a6-470c-9a0d-7d6f1da32991)

**Comment by dh1011** [comment]
Hi @bettergenius1,
Try running the command with tag 1.0.0: `docker run -p 3000:3000 dh1011/subscription-manager:1.0.0`. 
This image is compatible with the amd64 architecture. I plan to create builds for all tags soon.
