### ISSUE TITLE
Self-hosted NTFY server

### ISSUE THREAD

**Issue by uatevahr** [dh1011/subscription-manager#9]
Can you please add the possibility to change the default NTFY server with a self-hosted one. Thank you

**Comment by CopyAce** [comment]
Just fire up a docker container of NTFY on your server. Now your self hosted. Its pretty easy to setup and seems to work pretty good.

**Comment by uatevahr** [comment]
I already have one, but using the topic for a self-hosted server does not work in subscription manager.

**Comment by CopyAce** [comment]
Why not? I typed in a topic name in Subscription manager, then entered it into the self hosted NTFY. Test message goes through perfectly. Test your NTFY server by subscribing to your username "uatevahr" and see if you receive my test message.

**Comment by uatevahr** [comment]
I did not receive the notification. I will leave the subscription for now, if you want to try again.

**Comment by CopyAce** [comment]
Do you have the browser extension installed to pass the alert to your browser as well? Try sending a Test message to this topic name that you have subscribed to. You should have that option within NTFY if you use the right click or pancake options of that subscription, once its selected. If you want to create a subscription in NTFY and create a message I can try to PULL it to confirm you have WAN transmission.

**Comment by uatevahr** [comment]
i don't have a browser extension, i just sent a test notification from the phone (i have the app installed) and i got the test message on the phone and web page. 

The functionality is not the problem, i tested Sub Manager with a topic on topic-name (https://ntfy.sh/topic-name), just does not work with https://ntfy.DDNSname.synology.me/topic-name.

**Comment by brianmaddox** [comment]
Not to pile on, but I just noticed the same behavior.  Newly installed subscription-manager server and a newly installed local NTFY server (thanks to marius).  I tried setting the NTFY topic to http://<internal-address and port>/subman and https://<external-address>/subman and both fail.  Is Subscription-Manager only using the ntfy.sh hosted service?

**Comment by CopyAce** [comment]
Yes, it is. NTFY.topic-name server, then it relays to your self-hosted server.

**Comment by brianmaddox** [comment]
> Yes, it is. NTFY.topic-name, then it relays to your self-hosted server. 

I am not following. Can you provide an example of what should go in the subscription manager Ntfy feild?

**Comment by CopyAce** [comment]
Create any topic name you want in Subscription manager, then go to your NTFY server, click on Subscribe to topic, type in the same topic name you entered in Sub Manager, now click on the slider for "use another server", then click in the server address field, it pops up Https://ntfy.sh, select that, done.

**Comment by uatevahr** [comment]
What is the point of using self-hosted server if you want us to use the public ntfy. sh server?

**Comment by CopyAce** [comment]
Since the Subscription manager application doesn't have the option to choose a private server, the PUT/PUSH requests are relaying through NTFY, that you can then pickup with your self-hosted server.

**Comment by dh1011** [comment]
Hi @uatevahr 
Thank you for your suggestion. I agree that having the option to use a self-hosted NTFY server would be beneficial. I have added a setting to specify the NTFY server in the Notification settings (see attached image). You can test this feature in the branch `dh1011/subscription-manager:notification`


![image](https://github.com/user-attachments/assets/2596a1cd-9809-4ea3-9a8e-ed11d04ce238)

**Comment by uatevahr** [comment]
@dh1011 this worked like a charm.

Please add this to the currency build so we can use both features.

Thank you so much.

**Comment by CopyAce** [comment]
I can confirm as well that it works as intended. Can you combine this with :subscriptionlist-improve? Please.

**Comment by dh1011** [comment]
Hi al',
I've incorporated all the features into the `latest` tag. You can give it a try using `dh1011/subscription-manager` or `dh1011/subscription-manager:1.1.0` image.

Thank you all for the fantastic suggestions!

**Comment by cdestefano** [comment]
Not sure if this is the right place, but incase anyone stumbles on this issue while trying to talk to ntfy with auth, you can use a query parameter since the request headers aren't available.  Looking at ntfy [documentation](https://docs.ntfy.sh/publish/?h=auth#query-param): encode your token using base64: 

```
echo -n "Bearer tk_fullToken" | base64 | tr -d '='
```

In the `NTFY Topic` box, append the value with `?auth=base64EncodedToken` assuming `subscription-manager` topic, the full value would be `subscription-manager?auth=base64EncodedToken`

Thanks for the great app!
